name: esewa_flutter
description: An un-official Flutter plugin for eSewa Payment Gateway, integrate with ease and without any hassle.
version: 1.1.2
license: MIT
issue_tracker: https://github.com/iamnabink/flutter_esewa/issues
homepage: https://github.com/iamnabink/flutter_esewa
screenshots:
  - description: 'Flutter eSewa Package Cover'
    path: screenshots/cover.png
  - description: 'Esewa Payment Screen with Flutter Esewa Package'
    path: screenshots/payment_screen.png

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3 # 5.7.2+3 A Flutter plugin that allows you to add an inline webview, to use an headless webview, and to open an in-app browser window.


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  assets:
    - LICENSE
